### ISSUE TITLE
What I made wrong?

### ISSUE THREAD

**Issue by Dengranzy** [zVictorium/Minecraft-Mod-Translator#1]
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from deep-translator==1.11.4->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator==1.11.4->-r requirements.txt (line 1)) (2.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (2024.2.2)
WARNING: You are using pip version 20.1.1; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\Dengranz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\\main.py", line 6, in <module>
    settings = Settings()
  File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\scripts\settings.py", line 55, in __init__
    config_data[ORIGINAL_LANG]
  File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\scripts\settings.py", line 107, in _format_lang
    language, region = mc_lang.split('_')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Dengranzy** [comment]
> Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from deep-translator==1.11.4->-r requirements.txt (line 1)) (2.31.0) Requirement already satisfied: soupsieve>1.2 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator==1.11.4->-r requirements.txt (line 1)) (2.4.1) Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (2.0.7) Requirement already satisfied: idna<4,>=2.5 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (3.7) Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (3.3.2) Requirement already satisfied: certifi>=2017.4.17 in c:\users\dengranz\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests<3.0.0,>=2.23.0->deep-translator==1.11.4->-r requirements.txt (line 1)) (2024.2.2) WARNING: You are using pip version 20.1.1; however, version 24.0 is available. You should consider upgrading via the 'C:\Users\Dengranz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command. Traceback (most recent call last): File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\main.py", line 6, in settings = Settings() File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\scripts\settings.py", line 55, in **init** config_data[ORIGINAL_LANG] File "C:\Users\Dengranz\Робочий стіл\ServerS\translator mod\scripts\settings.py", line 107, in _format_lang language, region = mc_lang.split('_') ValueError: not enough values to unpack (expected 2, got 1)

**Comment by miosaurio** [comment]
Hey , i have the same problem , how you solve it ?
